services:

  smoker-app:
    image: ghcr.io/swimmingnoah/smoker-app:latest
    container_name: smoker-app
    ports:
      - "3001:80"
    env_file:
      - .env
    volumes:
      - smoker-uploads:/app/uploads
    restart: unless-stopped

volumes:
  smoker-uploads:
